**Phys 239 Final Project**

By:  Mladen Kolovic(20463338) & Mohesan Sreekuladevan (20478773)

The objective of this notebook is to create a class that would help calculate and display the Electrodynamics between charged particles.

In [5]:
import numpy as np
a=np.arange(0,10)
print(a)
print(a**2)
print(a-2)
print(a+a)
print(a/a)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]
[-2 -1  0  1  2  3  4  5  6  7]
[ 0  2  4  6  8 10 12 14 16 18]
[ nan   1.   1.   1.   1.   1.   1.   1.   1.   1.]


C:\Users\mohe_\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: RuntimeWarning: invalid value encountered in true_divide
